"""widen jshir and add camera_code

Revision ID: 4b67d38f25db
Revises: d1fab23ead23
Create Date: 2026-09-09 17:07:53.714740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b67d38f25db'
down_revision: Union[str, Sequence[str], None] = 'd1fab23ead23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('camera_code', sa.String(length=32), nullable=True))
    op.alter_column('employees', 'jshir',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.create_unique_constraint(None, 'employees', ['camera_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.alter_column('employees', 'jshir',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    op.drop_column('employees', 'camera_code')
    # ### end Alembic commands ###
