"""make employee first_name and last_name nullable

Revision ID: d1fab23ead23
Revises: 16c16f524506
Create Date: 2026-09-08 08:28:53.161041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fab23ead23'
down_revision: Union[str, Sequence[str], None] = '16c16f524506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Backfill NULLs introduced while the columns were optional, otherwise
    # restoring NOT NULL fails on any unnamed employee.
    op.execute("UPDATE employees SET first_name = '' WHERE first_name IS NULL")
    op.execute("UPDATE employees SET last_name = '' WHERE last_name IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
