"""add_work_rate_to_employee

Revision ID: 801f36e7b633
Revises: edbcc51a427a
Create Date: 2026-06-10 17:08:14.079835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801f36e7b633'
down_revision: Union[str, Sequence[str], None] = 'edbcc51a427a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('work_rate', sa.Float(), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'work_rate')
    # ### end Alembic commands ###
