"""Add image paths to user events

Revision ID: 2bc797c12eec
Revises: d64110a616dd
Create Date: 2026-03-17 06:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc797c12eec'
down_revision: Union[str, None] = 'd64110a616dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_events', sa.Column('enter_image_path', sa.String(), nullable=True))
    op.add_column('user_events', sa.Column('exit_image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_events', 'exit_image_path')
    op.drop_column('user_events', 'enter_image_path')
    # ### end Alembic commands ###
