"""add_position_and_department

Revision ID: edbcc51a427a
Revises: d4e5f6072139
Create Date: 2026-06-10 16:15:51.651671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbcc51a427a'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6072139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('work_schedule_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_schedule_id'], ['work_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('employees', sa.Column('position_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))

    # Data Migration: Transfer positions
    op.execute("""
        INSERT INTO positions (name)
        SELECT DISTINCT position FROM employees 
        WHERE position IS NOT NULL AND position != ''
        ON CONFLICT (name) DO NOTHING
    """)

    # Data Migration: Transfer departments
    op.execute("""
        INSERT INTO departments (name)
        SELECT DISTINCT department FROM employees 
        WHERE department IS NOT NULL AND department != ''
        ON CONFLICT (name) DO NOTHING
    """)

    # Data Migration: Set work_schedule_id in departments based on existing employees' schedules
    op.execute("""
        UPDATE departments d
        SET work_schedule_id = (
            SELECT work_schedule_id FROM employees e
            WHERE e.department = d.name AND e.work_schedule_id IS NOT NULL
            LIMIT 1
        )
    """)

    # Data Migration: Map employees to their new position_id
    op.execute("""
        UPDATE employees e
        SET position_id = p.id
        FROM positions p
        WHERE e.position = p.name
    """)

    # Data Migration: Map employees to their new department_id
    op.execute("""
        UPDATE employees e
        SET department_id = d.id
        FROM departments d
        WHERE e.department = d.name
    """)

    op.drop_constraint(op.f('fk_employees_work_schedule_id'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'positions', ['position_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_column('employees', 'department')
    op.drop_column('employees', 'work_schedule_id')
    op.drop_column('employees', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('position', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('work_schedule_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('department', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # Data Migration (Downgrade): Restore text position names
    op.execute("""
        UPDATE employees e
        SET position = p.name
        FROM positions p
        WHERE e.position_id = p.id
    """)

    # Data Migration (Downgrade): Restore text department names
    op.execute("""
        UPDATE employees e
        SET department = d.name
        FROM departments d
        WHERE e.department_id = d.id
    """)

    # Data Migration (Downgrade): Restore work_schedule_id
    op.execute("""
        UPDATE employees e
        SET work_schedule_id = d.work_schedule_id
        FROM departments d
        WHERE e.department_id = d.id
    """)

    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('fk_employees_work_schedule_id'), 'employees', 'work_schedules', ['work_schedule_id'], ['id'], ondelete='SET NULL')
    op.drop_column('employees', 'department_id')
    op.drop_column('employees', 'position_id')
    op.drop_table('departments')
    op.drop_table('positions')
    # ### end Alembic commands ###
